name: morse_code_generator
description: A Flutter package for converting text between English and Morse code, supporting real-time translation, custom patterns, and educational use cases for learners and developers.F
version: 1.0.0
homepage: https://github.com/Suneel-DK/morse_code_generator

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

